version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v1-{{ checksum "package.json" }}
            - deps-v1-
      - run:
          name: Install dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            npm install -g --silent cuttlebelle
            npm install
            node patches/fix-cuttlebelle-del.js
            git config user.email "ci-build@orbs.com"
            git config user.name "ci-build"
      - save_cache:
          key: deps-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - restore_cache:
          keys:
            - site-v2-{{ .Branch }}
            - site-v2-
      - add_ssh_keys:
          fingerprints:
            - "75:7f:ea:52:21:2e:9d:7f:e0:b5:36:d2:6d:6b:98:ae"
      - run:
          name: Build
          command: make build
          no_output_timeout: 60m
      - save_cache:
          key: site-v2-{{ .Branch }}-{{ epoch }}
          paths:
            - site
            - .build-hashes
      - run:
          name: Create CNAME file. $DEPLOY_DOMAIN_NAME is defined on circleci project env variables.
          command: echo $DEPLOY_DOMAIN_NAME > ./site/CNAME
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --message "[ci skip] Deploy" --dist site

workflows:
  version: 2
  build:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
